markdown: redcarpet
highligter: pygments
safe: false


description: "Coding, startups and ideas."
logo: false
meta_description: "Ognjen's Blog. Coding, startups and ideas."

paginate: 15
# Details for the RSS feed generator
name:           Ognjen's Blog
url:            'http://gognjen.github.io'
author:         'Ognjen Glišić'
rss_path: 		'/'
