name: Ognjen's Blog
description: Coding, startups and ideas
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
highligter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://gognjen.github.io'
author:         'Ognjen Glišić'
